[1] "Starting at 2025-05-29 19:54:29.467915"
[1] "tools/exomedepth/exomedepthParams.yaml"
[2] "datasets.yaml"                         
[3] "true"                                  
[1] "Params for this execution: list(phi.bins = 1, n.bins.reduced = 10000, transition.probability = 1e-04, expected.CNV.length = 50000)"
[1] "Datasets for this execution: list(dataset1 = list(include = FALSE, bams_dir = \"/yourPath/bams/\", bed_file = \"/yourPath/bed5.bed\", annotated_bed_file = \"/yourPath/annotated.bed.bed\", fasta_file = \"/yourPath/GRCh37_Ensembl_67.fa\", fasta_dict = \"/yourPath/GRCh37_Ensembl_67.dict\", validated_results_file = \"/yourPath/MLPAresults.txt\", validated_results_file_format = \"icr\", read_length = 101), mydataset = list(include = TRUE, bams_dir = \"/CNV/Sample_data/Shahryar_samples/\", bed_file = \"/CNV/clinvarCnv_PGfiltered_4col.bed\", annotated_bed_file = \"/annotated.bed.bed\", \n    fasta_file = \"/CNV/ref/Homo_sapiens_assembly38.fasta\", fasta_dict = \"/yourPath/GRCh37_Ensembl_67.dict\", validated_results_file = \"/CNV/CNVbenchmarkeR/ValidataionResult_CSR.csv\", validated_results_file_format = \"icr\", read_length = 101))"
[1] "Starting ExomeDepth for mydataset dataset"
Error in scan(file = file, what = what, sep = sep, quote = quote, dec = dec,  : 
  line 1 did not have 4 elements
Calls: read.table -> scan
Execution halted
